// scripts/build-db.mjs
//
// Unified build script for Discworld Cowtography.
// Downloads Quow's quow_cowbar.zip (or accepts a local --db path), then:
//   - Generates ui/data/rooms.js      — JS module for the map panel
//   - Generates src/data/*.lua        — Lua tables for DB search
//   - Copies ui/maps/*.png            — map tile images
//
// Run: node scripts/build-db.mjs
// With local DB: node scripts/build-db.mjs --db /path/to/_quowmap_database.db
// With local zip: node scripts/build-db.mjs --zip /path/to/quow_cowbar.zip

import { promises as fs, writeFileSync, mkdirSync } from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import { fileURLToPath } from 'node:url'
import AdmZip from 'adm-zip'
import Database from 'better-sqlite3'

const QUOW_URL = 'https://quow.co.uk/quow_cowbar.zip'
const LUA_HEADER = '-- Auto-generated by scripts/build-db.mjs. Do not edit by hand.\n'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = path.resolve(__dirname, '..')
const OUT_ROOMS_JS  = path.join(REPO_ROOT, 'ui', 'data', 'rooms.js')
const OUT_MAPS_DIR  = path.join(REPO_ROOT, 'ui', 'maps')
const OUT_LUA_DIR   = path.join(REPO_ROOT, 'src', 'data')

// ─── Lua generators ──────────────────────────────────────────────────────────

function luaStr(s) {
  if (s == null) return "''"
  return "'" + String(s)
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '')
    .replace(/\0/g, '') + "'"
}

export function generateRoomsLua(db) {
  const rows = db.prepare('SELECT room_id, room_short FROM rooms').all()
  const lines = [LUA_HEADER + 'return {']
  for (const row of rows) {
    lines.push(`  [${luaStr(row.room_id)}] = ${luaStr(row.room_short)},`)
  }
  lines.push('}')
  return lines.join('\n')
}

export function generateItemsLua(db) {
  const rows = db.prepare(`
    SELECT si.item_name, si.room_id, si.sale_price, r.room_short
    FROM shop_items si
    JOIN rooms r ON si.room_id = r.room_id
    ORDER BY si.item_name COLLATE NOCASE
  `).all()
  const lines = [LUA_HEADER + 'return {']
  for (const row of rows) {
    lines.push(`  { name = ${luaStr(row.item_name)}, room_id = ${luaStr(row.room_id)}, location = ${luaStr(row.room_short)}, price = ${luaStr(row.sale_price ?? '')} },`)
  }
  lines.push('}')
  return lines.join('\n')
}

export function generateNpcsLua(db) {
  const rows = db.prepare(`
    SELECT ni.npc_name, ni.room_id, r.room_short
    FROM npc_info ni
    JOIN rooms r ON ni.room_id = r.room_id
    ORDER BY ni.npc_name COLLATE NOCASE
  `).all()
  const lines = [LUA_HEADER + 'return {']
  for (const row of rows) {
    lines.push(`  { name = ${luaStr(row.npc_name)}, room_id = ${luaStr(row.room_id)}, location = ${luaStr(row.room_short)} },`)
  }
  lines.push('}')
  return lines.join('\n')
}

export function generateNpcItemsLua(db) {
  const rows = db.prepare(`
    SELECT nit.item_name, ni.npc_name, ni.room_id, r.room_short, nit.sale_price
    FROM npc_items nit
    JOIN npc_info ni ON nit.npc_id = ni.npc_id
    JOIN rooms r ON ni.room_id = r.room_id
    ORDER BY nit.item_name COLLATE NOCASE
  `).all()
  const lines = [LUA_HEADER + 'return {']
  for (const row of rows) {
    lines.push(`  { name = ${luaStr(row.item_name)}, npc = ${luaStr(row.npc_name)}, room_id = ${luaStr(row.room_id)}, location = ${luaStr(row.room_short)}, price = ${luaStr(row.sale_price ?? '')} },`)
  }
  lines.push('}')
  return lines.join('\n')
}

export function generateMapNamesLua(db, maps) {
  const rows = db.prepare('SELECT room_id, map_id FROM rooms').all()
  const lines = [LUA_HEADER + 'return {']
  for (const row of rows) {
    const name = maps[row.map_id]?.name ?? 'Unknown'
    lines.push(`  [${luaStr(row.room_id)}] = ${luaStr(name)},`)
  }
  lines.push('}')
  return lines.join('\n')
}

export function generateExitsLua(db) {
  const rows = db.prepare('SELECT room_id, connect_id, exit FROM room_exits').all()
  const byRoom = new Map()
  for (const row of rows) {
    if (!byRoom.has(row.room_id)) byRoom.set(row.room_id, [])
    byRoom.get(row.room_id).push({ neighbor: row.connect_id, dir: row.exit })
  }
  const lines = [LUA_HEADER + 'return {']
  for (const [roomId, exits] of byRoom) {
    const parts = exits.map(e => `[${luaStr(e.neighbor)}] = ${luaStr(e.dir)}`).join(', ')
    lines.push(`  [${luaStr(roomId)}] = { ${parts} },`)
  }
  lines.push('}')
  return lines.join('\n')
}

// ─── JS generator ────────────────────────────────────────────────────────────

function readRoomsTable(db) {
  const rows = db.prepare('SELECT room_id, map_id, xpos, ypos, room_short FROM rooms').all()
  if (rows.length < 5000) {
    console.warn(`[build] WARNING: rooms table has only ${rows.length} rows; expected >5000. Continuing.`)
  }
  const out = {}
  for (const r of rows) {
    out[r.room_id] = [r.map_id, r.xpos, r.ypos, r.room_short]
  }
  return out
}

function parseMapfilesTable(xml) {
  const blockMatch = xml.match(/sQuowMapfiles\s*=\s*\{([\s\S]*?)\n\}/)
  if (!blockMatch) throw new Error('Could not locate sQuowMapfiles table in QuowMinimap.xml')
  const block = blockMatch[1]
  const out = {}
  const rowRe = /\[(\d+)\]\s*=\s*\{\s*"([^"]+)"\s*,\s*"([^"]+)"\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*"([^"]+)"\s*,\s*(?:true|false)\s*,\s*\d+\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(true|false)/g
  let m
  while ((m = rowRe.exec(block)) !== null) {
    const id = Number(m[1])
    out[id] = {
      file: m[2], name: m[3],
      defaultX: Number(m[6]), defaultY: Number(m[7]),
      region: m[8],
      maxX: Number(m[9]), maxY: Number(m[10]),
      topLevel: m[11] === 'true',
    }
  }
  if (Object.keys(out).length < 20) {
    throw new Error(`Parsed only ${Object.keys(out).length} maps from sQuowMapfiles; expected >60. Format may have changed.`)
  }
  return out
}

function terrainConstants(xml) {
  // Parsed from the line initializing the terrain-projection variables, e.g.:
  //   sPreviousApparentRoomID, iScaleX, iScaleY, iHubX, iHubY = "", 103488, 103488, 2840, 3639
  const m = xml.match(
    /iScaleX,\s*iScaleY,\s*iHubX,\s*iHubY\s*=\s*"[^"]*"\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)/
  )
  if (!m) throw new Error('Could not locate iScaleX/iScaleY/iHubX/iHubY initializer in QuowMinimap.xml')
  return {
    hubX: Number(m[3]), hubY: Number(m[4]),
    scaleX: Number(m[1]), scaleY: Number(m[2]),
    viewportMapId: 99,
  }
}

function emitRoomsModule({ rooms, maps, terrain }) {
  const today = new Date().toISOString().slice(0, 10)
  const header = `// Auto-generated by scripts/build-db.mjs.
// Source: QuowMinimap.xml + _quowmap_database.db
// Downloaded from ${QUOW_URL} on ${today}.
// Do not edit by hand — re-run \`npm run build:data\` to refresh.

export const schemaVersion = 1;
`
  const mapsLines = ['export const maps = {']
  for (const id of Object.keys(maps).map(Number).sort((a, b) => a - b)) {
    mapsLines.push(`  ${id}: ${JSON.stringify(maps[id])},`)
  }
  mapsLines.push('};\n')

  const roomLines = ['export const rooms = {']
  for (const id of Object.keys(rooms).sort()) {
    roomLines.push(`  ${JSON.stringify(id)}: ${JSON.stringify(rooms[id])},`)
  }
  roomLines.push('};\n')

  const terrainBlock = `export const terrain = ${JSON.stringify(terrain, null, 2)};\n`
  return [header, mapsLines.join('\n'), roomLines.join('\n'), terrainBlock].join('\n')
}

// ─── Download + unzip ────────────────────────────────────────────────────────

async function downloadZip(url, dest) {
  console.log(`[build] downloading ${url}`)
  const res = await fetch(url)
  if (!res.ok) throw new Error(`fetch ${url} → HTTP ${res.status}`)
  const buf = Buffer.from(await res.arrayBuffer())
  await fs.writeFile(dest, buf)
  console.log(`[build] saved ${buf.length} bytes → ${dest}`)
}

function unzipTo(zipPath, destDir) {
  const zip = new AdmZip(zipPath)
  zip.extractAllTo(destDir, /* overwrite */ true)
}

async function assertExists(p, label) {
  try { await fs.access(p) }
  catch { throw new Error(`Expected ${label} at ${p}; got missing. Did Quow restructure the zip?`) }
}

async function copyPngs(srcDir, destDir) {
  await fs.mkdir(destDir, { recursive: true })
  const entries = await fs.readdir(srcDir)
  let copied = 0
  for (const name of entries) {
    if (!name.toLowerCase().endsWith('.png')) continue
    await fs.copyFile(path.join(srcDir, name), path.join(destDir, name))
    copied++
  }
  console.log(`[build] copied ${copied} PNGs → ${destDir}`)
}

// ─── Main ────────────────────────────────────────────────────────────────────

async function main() {
  const args = process.argv.slice(2)

  let dbPath = null
  let xmlPath = null
  let pngsDir = null

  const dbFlagIdx  = args.indexOf('--db')
  const zipFlagIdx = args.indexOf('--zip')

  if (dbFlagIdx !== -1) {
    // Local DB path provided; no XML = skip JS generation, no PNGs = skip PNG copy.
    dbPath = path.resolve(args[dbFlagIdx + 1])
    console.log(`[build] using local DB: ${dbPath}`)
  } else {
    // Download zip (or use --zip local path) and extract.
    let zipPath
    if (zipFlagIdx !== -1) {
      zipPath = path.resolve(args[zipFlagIdx + 1])
      console.log(`[build] using local zip: ${zipPath}`)
    } else {
      const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'mallard-cowtography-build-'))
      console.log(`[build] working dir: ${tmpDir}`)
      zipPath = path.join(tmpDir, 'quow_cowbar.zip')
      await downloadZip(QUOW_URL, zipPath)
    }

    const unpackDir = zipPath.replace(/\.zip$/, '-unpacked')
    await fs.mkdir(unpackDir, { recursive: true })
    unzipTo(zipPath, unpackDir)

    dbPath  = path.join(unpackDir, 'maps', '_quowmap_database.db')
    xmlPath = path.join(unpackDir, 'QuowMinimap.xml')
    pngsDir = path.join(unpackDir, 'maps')

    await assertExists(dbPath,  '_quowmap_database.db')
    await assertExists(xmlPath, 'QuowMinimap.xml')
  }

  const db = new Database(dbPath, { readonly: true })
  mkdirSync(OUT_LUA_DIR, { recursive: true })

  // Lua tables
  const luaGenerators = [
    ['rooms.lua',     generateRoomsLua],
    ['items.lua',     generateItemsLua],
    ['npcs.lua',      generateNpcsLua],
    ['npc_items.lua', generateNpcItemsLua],
    ['exits.lua',     generateExitsLua],
  ]
  for (const [filename, gen] of luaGenerators) {
    writeFileSync(path.join(OUT_LUA_DIR, filename), gen(db), 'utf8')
    console.log(`[build]   ✓ src/data/${filename}`)
  }

  // JS module + PNGs (only when we have the full zip extraction)
  if (xmlPath) {
    const xml       = await fs.readFile(xmlPath, 'utf8')
    const roomsData = readRoomsTable(db)
    const maps      = parseMapfilesTable(xml)
    const terrain   = terrainConstants(xml)

    await fs.mkdir(path.dirname(OUT_ROOMS_JS), { recursive: true })
    await fs.writeFile(OUT_ROOMS_JS, emitRoomsModule({ rooms: roomsData, maps, terrain }), 'utf8')
    console.log(`[build]   ✓ ui/data/rooms.js  (${Object.keys(roomsData).length} rooms, ${Object.keys(maps).length} maps)`)

    await copyPngs(pngsDir, OUT_MAPS_DIR)
  } else {
    console.log('[build]   (skipping ui/data/rooms.js and PNGs — --db mode, no XML available)')
  }

  db.close()
  console.log('[build] done.')
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch(e => { console.error(`[build] FAILED: ${e.message}`); process.exit(1) })
}
