import { fileURLToPath } from 'url'
import { resolve, dirname, join } from 'path'
import { writeFileSync, mkdirSync } from 'fs'
import Database from 'better-sqlite3'

const HEADER = '-- Auto-generated by scripts/build-db.mjs. Do not edit by hand.\n'

function luaStr(s) {
  if (s == null) return "''"
  return "'" + String(s)
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '')
    .replace(/\0/g, '') + "'"
}

export function generateRoomsLua(db) {
  const rows = db.prepare('SELECT room_id, room_short FROM rooms').all()
  const lines = [HEADER + 'return {']
  for (const row of rows) {
    lines.push(`  [${luaStr(row.room_id)}] = ${luaStr(row.room_short)},`)
  }
  lines.push('}')
  return lines.join('\n')
}
